### ISSUE TITLE
Post number of YouTube subscribers to Slack

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/youtube-slack-bot#1]
As video creators, we'd like to see a every week day at 08:00 that shows the number of YouTube subscribers

**Comment by mschwartz** [comment]
Why not hourly?

**Comment by mschwartz** [comment]
Also shows views and delta views (delta from last hour)

**Comment by mschwartz** [comment]
https://github.com/ModusCreateOrg/youtube-slack-bot/pull/11
