### ISSUE TITLE
Post a message to slack when a top-level comment is made on someone's YouTube video

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/youtube-slack-bot#3]
As video creators, we'd like to get notified directly via Slack when a comment is made on our videos.

**Comment by mschwartz** [comment]
Polling is done hourly.  Status is kept in MongoDB.

**Comment by mschwartz** [comment]
PR #7 New Comments

**Comment by mschwartz** [comment]
Note: polling is done every hour
